#!/usr/bin/env bash
# Summary: Show the current Perl6 version and its origin
#
# Shows the currently selected Perl6 version and how it was
# selected. To obtain only the version string, use `p6env
# version-name'.

set -e
[ -n "$P6ENV_DEBUG" ] && set -x

echo "$(p6env-version-name) (set by $(p6env-version-origin))"
