#!/usr/bin/env bash
#
# Summary: Display the full path to an executable
#
# Usage: p6env which <command>
#
# Displays the full path to the executable that p6env will invoke when
# you run the given command.

set -e
[ -n "$P6ENV_DEBUG" ] && set -x

# Provide p6env completions
if [ "$1" = "--complete" ]; then
  exec p6env-shims --short
fi

remove_from_path() {
  local path_to_remove="$1"
  local path_before
  local result=":${PATH//\~/$HOME}:"
  while [ "$path_before" != "$result" ]; do
    path_before="$result"
    result="${result//:$path_to_remove:/:}"
  done
  result="${result%:}"
  echo "${result#:}"
}

P6ENV_COMMAND="$1"

if [ -z "$P6ENV_COMMAND" ]; then
  p6env-help --usage which >&2
  exit 1
fi

P6ENV_VERSION="${P6ENV_VERSION:-$(p6env-version-name)}"

if [ "$P6ENV_VERSION" = "system" ]; then
  PATH="$(remove_from_path "${P6ENV_ROOT}/shims")" \
    P6ENV_COMMAND_PATH="$(command -v "$P6ENV_COMMAND" || true)"
else
  P6ENV_COMMAND_PATH="${P6ENV_ROOT}/versions/${P6ENV_VERSION}/bin/${P6ENV_COMMAND}"
  if [ ! -x "$P6ENV_COMMAND_PATH" ]; then
    P6ENV_COMMAND_PATH="${P6ENV_ROOT}/versions/${P6ENV_VERSION}/share/perl6/site/bin/${P6ENV_COMMAND}"
  fi
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`p6env-hooks which`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -x "$P6ENV_COMMAND_PATH" ]; then
  echo "$P6ENV_COMMAND_PATH"
elif [ "$P6ENV_VERSION" != "system" ] && [ ! -d "${P6ENV_ROOT}/versions/${P6ENV_VERSION}" ]; then
  echo "p6env: version \`$P6ENV_VERSION' is not installed (set by $(p6env-version-origin))" >&2
  exit 1
else
  echo "p6env: $P6ENV_COMMAND: command not found" >&2

  versions="$(p6env-whence "$P6ENV_COMMAND" || true)"
  if [ -n "$versions" ]; then
    { echo
      echo "The \`$1' command exists in these Perl6 versions:"
      echo "$versions" | sed 's/^/  /g'
      echo
    } >&2
  fi

  exit 127
fi
