#!/usr/bin/env bash
# Usage: p6env completions <command> [arg1 arg2...]

set -e
[ -n "$P6ENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  p6env-help --usage completions >&2
  exit 1
fi

# Provide p6env completions
if [ "$COMMAND" = "--complete" ]; then
  exec p6env-commands
fi

COMMAND_PATH="$(command -v "p6env-$COMMAND" || command -v "p6env-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide p6env completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
