#!/usr/bin/env bash
# Usage: p6env version-file [<dir>]
# Summary: Detect the file that sets the current p6env version
set -e
[ -n "$P6ENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -s "${root}/.perl6-version" ]; then
      echo "${root}/.perl6-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$P6ENV_DIR" || {
    [ "$P6ENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${P6ENV_ROOT}/version"
fi
