#!/usr/bin/env bash
# Summary: Show the current Perl6 version
set -e
[ -n "$P6ENV_DEBUG" ] && set -x

if [ -z "$P6ENV_VERSION" ]; then
  P6ENV_VERSION_FILE="$(p6env-version-file)"
  P6ENV_VERSION="$(p6env-version-file-read "$P6ENV_VERSION_FILE" || true)"
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`p6env-hooks version-name`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -z "$P6ENV_VERSION" ] || [ "$P6ENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${P6ENV_ROOT}/versions/${version}" ]
}

if version_exists "$P6ENV_VERSION"; then
  echo "$P6ENV_VERSION"
elif version_exists "${P6ENV_VERSION#perl6-}"; then
  echo "${P6ENV_VERSION#perl6-}"
else
  echo "p6env: version \`$P6ENV_VERSION' is not installed (set by $(p6env-version-origin))" >&2
  exit 1
fi
