#!/usr/bin/env bash
set -e
[ -n "$P6ENV_DEBUG" ] && set -x

# Provide p6env completions
if [ "$1" = "--complete" ]; then
  exec p6env-rehash --complete
fi

shell="$(basename "${P6ENV_SHELL:-$SHELL}")"

# When p6env shell integration is enabled, delegate to p6env-rehash,
# then tell the shell to empty its command lookup cache.
p6env-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
