#!/usr/bin/env bash
# Summary: List hook scripts for a given p6env command
# Usage: p6env hooks <command>

set -e
[ -n "$P6ENV_DEBUG" ] && set -x

# Provide p6env completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo version-name
  echo version-origin
  echo which
  exit
fi

P6ENV_COMMAND="$1"
if [ -z "$P6ENV_COMMAND" ]; then
  p6env-help --usage hooks >&2
  exit 1
fi

if ! enable -f "${BASH_SOURCE%/*}"/p6env-realpath.dylib realpath 2>/dev/null; then
  if [ -n "$P6ENV_NATIVE_EXT" ]; then
    echo "p6env: failed to load \`realpath' builtin" >&2
    exit 1
  fi
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "p6env: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

realpath() {
  local cwd="$PWD"
  local path="$1"
  local name

  while [ -n "$path" ]; do
    name="${path##*/}"
    [ "$name" = "$path" ] || cd "${path%/*}"
    path="$(resolve_link "$name" || true)"
  done

  echo "${PWD}/$name"
  cd "$cwd"
}
fi

IFS=: hook_paths=($P6ENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$P6ENV_COMMAND"/*.bash; do
    realpath "$script"
  done
done
shopt -u nullglob
