#!/usr/bin/env bash
# Summary: List all Perl6 versions that contain the given executable
# Usage: p6env whence [--path] <command>

set -e
[ -n "$P6ENV_DEBUG" ] && set -x

# Provide p6env completions
if [ "$1" = "--complete" ]; then
  echo --path
  exec p6env-shims --short
fi

if [ "$1" = "--path" ]; then
  print_paths="1"
  shift
else
  print_paths=""
fi

whence() {
  local command="$1"
  p6env-versions --bare | while read -r version; do
    path="$(p6env-prefix "$version")/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
    path="$(p6env-prefix "$version")/share/perl6/site/bin/${command}"
    if [ -x "$path" ]; then
      [ "$print_paths" ] && echo "$path" || echo "$version"
    fi
  done
}

P6ENV_COMMAND="$1"
if [ -z "$P6ENV_COMMAND" ]; then
  p6env-help --usage whence >&2
  exit 1
fi

result="$(whence "$P6ENV_COMMAND")"
[ -n "$result" ] && echo "$result"
