#!/usr/bin/env bash
#
# Summary: Set or show the global Raku version
#
# Usage: rakuenv global <version>
#
# Sets the global Raku version. You can override the global version at
# any time by setting a directory-specific version with `rakuenv local'
# or by setting the `RAKUENV_VERSION' environment variable.
#
# <version> should be a string matching a Raku version known to rakuenv.
# The special version string `system' will use your default system Raku.
# Run `rakuenv versions' for a list of available Raku versions.

set -e
[ -n "$RAKUENV_DEBUG" ] && set -x

# Provide rakuenv completions
if [ "$1" = "--complete" ]; then
  echo system
  exec rakuenv-versions --bare
fi

RAKUENV_VERSION="$1"
RAKUENV_VERSION_FILE="${RAKUENV_ROOT}/version"

if [ -n "$RAKUENV_VERSION" ]; then
  rakuenv-version-file-write "$RAKUENV_VERSION_FILE" "$RAKUENV_VERSION"
else
  rakuenv-version-file-read "$RAKUENV_VERSION_FILE" || echo system
fi
