#!/usr/bin/env bash
#
# Summary: Set or show the shell-specific Raku version
#
# Usage: rakuenv shell <version>
#        rakuenv shell -
#        rakuenv shell --unset
#
# Sets a shell-specific Raku version by setting the `RAKUENV_VERSION'
# environment variable in your shell. This version overrides local
# application-specific versions and the global version.
#
# <version> should be a string matching a Raku version known to rakuenv.
# The special version string `system' will use your default system Raku.
# Run `rakuenv versions' for a list of available Raku versions.
#
# When `-` is passed instead of the version string, the previously set
# version will be restored. With `--unset`, the `RAKUENV_VERSION`
# environment variable gets unset, restoring the environment to the
# state before the first `rakuenv shell` call.

set -e
[ -n "$RAKUENV_DEBUG" ] && set -x

# Provide rakuenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec rakuenv-versions --bare
fi

version="$1"
shell="$(basename "${RAKUENV_SHELL:-$SHELL}")"

if [ -z "$version" ]; then
  if [ -z "$RAKUENV_VERSION" ]; then
    echo "rakuenv: no shell-specific version configured" >&2
    exit 1
  else
    echo 'echo "$RAKUENV_VERSION"'
    exit
  fi
fi

if [ "$version" = "--unset" ]; then
  case "$shell" in
  fish )
    echo 'set -gu RAKUENV_VERSION_OLD "$RAKUENV_VERSION"'
    echo "set -e RAKUENV_VERSION"
    ;;
  * )
    echo 'RAKUENV_VERSION_OLD="$RAKUENV_VERSION"'
    echo "unset RAKUENV_VERSION"
    ;;
  esac
  exit
fi

if [ "$version" = "-" ]; then
  case "$shell" in
  fish )
    cat <<EOS
if set -q RAKUENV_VERSION_OLD
  if [ -n "\$RAKUENV_VERSION_OLD" ]
    set RAKUENV_VERSION_OLD_ "\$RAKUENV_VERSION"
    set -gx RAKUENV_VERSION "\$RAKUENV_VERSION_OLD"
    set -gu RAKUENV_VERSION_OLD "\$RAKUENV_VERSION_OLD_"
    set -e RAKUENV_VERSION_OLD_
  else
    set -gu RAKUENV_VERSION_OLD "\$RAKUENV_VERSION"
    set -e RAKUENV_VERSION
  end
else
  echo "rakuenv: RAKUENV_VERSION_OLD is not set" >&2
  false
end
EOS
    ;;
  * )
    cat <<EOS
if [ -n "\${RAKUENV_VERSION_OLD+x}" ]; then
  if [ -n "\$RAKUENV_VERSION_OLD" ]; then
    RAKUENV_VERSION_OLD_="\$RAKUENV_VERSION"
    export RAKUENV_VERSION="\$RAKUENV_VERSION_OLD"
    RAKUENV_VERSION_OLD="\$RAKUENV_VERSION_OLD_"
    unset RAKUENV_VERSION_OLD_
  else
    RAKUENV_VERSION_OLD="\$RAKUENV_VERSION"
    unset RAKUENV_VERSION
  fi
else
  echo "rakuenv: RAKUENV_VERSION_OLD is not set" >&2
  false
fi
EOS
    ;;
  esac
  exit
fi

# Make sure the specified version is installed.
if rakuenv-prefix "$version" >/dev/null; then
  if [ "$version" != "$RAKUENV_VERSION" ]; then
    case "$shell" in
    fish )
      echo 'set -gu RAKUENV_VERSION_OLD "$RAKUENV_VERSION"'
      echo "set -gx RAKUENV_VERSION \"$version\""
      ;;
    * )
      echo 'RAKUENV_VERSION_OLD="$RAKUENV_VERSION"'
      echo "export RAKUENV_VERSION=\"$version\""
      ;;
    esac
  fi
else
  echo "false"
  exit 1
fi
