#!/usr/bin/env bash
# Summary: Show the current Raku version
set -e
[ -n "$RAKUENV_DEBUG" ] && set -x

if [ -z "$RAKUENV_VERSION" ]; then
  RAKUENV_VERSION_FILE="$(rakuenv-version-file)"
  RAKUENV_VERSION="$(rakuenv-version-file-read "$RAKUENV_VERSION_FILE" || true)"
fi

OLDIFS="$IFS"
IFS=$'\n' scripts=(`rakuenv-hooks version-name`)
IFS="$OLDIFS"
for script in "${scripts[@]}"; do
  source "$script"
done

if [ -z "$RAKUENV_VERSION" ] || [ "$RAKUENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

version_exists() {
  local version="$1"
  [ -d "${RAKUENV_ROOT}/versions/${version}" ]
}

if version_exists "$RAKUENV_VERSION"; then
  echo "$RAKUENV_VERSION"
elif version_exists "${RAKUENV_VERSION#raku-}"; then
  echo "${RAKUENV_VERSION#raku-}"
else
  echo "rakuenv: version \`$RAKUENV_VERSION' is not installed (set by $(rakuenv-version-origin))" >&2
  exit 1
fi
