#!/usr/bin/env bash
#
# Summary: Set or show the local application-specific Raku version
#
# Usage: rakuenv local <version>
#        rakuenv local --unset
#
# Sets the local application-specific Raku version by writing the
# version name to a file named `.raku-version'.
#
# When you run a Raku command, rakuenv will look for a `.raku-version'
# file in the current directory and each parent directory. If no such
# file is found in the tree, rakuenv will use the global Raku version
# specified with `rakuenv global'. A version specified with the
# `RAKUENV_VERSION' environment variable takes precedence over local
# and global versions.
#
# <version> should be a string matching a Raku version known to rakuenv.
# The special version string `system' will use your default system Raku.
# Run `rakuenv versions' for a list of available Raku versions.

set -e
[ -n "$RAKUENV_DEBUG" ] && set -x

# Provide rakuenv completions
if [ "$1" = "--complete" ]; then
  echo --unset
  echo system
  exec rakuenv-versions --bare
fi

RAKUENV_VERSION="$1"

if [ "$RAKUENV_VERSION" = "--unset" ]; then
  rm -f .raku-version
elif [ -n "$RAKUENV_VERSION" ]; then
  rakuenv-version-file-write .raku-version "$RAKUENV_VERSION"
else
  if version_file="$(rakuenv-version-file "$PWD")"; then
    rakuenv-version-file-read "$version_file"
  else
    echo "rakuenv: no local version configured for this directory" >&2
    exit 1
  fi
fi
