#!/usr/bin/env bash
# Usage: rakuenv version-file [<dir>]
# Summary: Detect the file that sets the current rakuenv version
set -e
[ -n "$RAKUENV_DEBUG" ] && set -x

target_dir="$1"

find_local_version_file() {
  local root="$1"
  while ! [[ "$root" =~ ^//[^/]*$ ]]; do
    if [ -s "${root}/.raku-version" ]; then
      echo "${root}/.raku-version"
      return 0
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
  return 1
}

if [ -n "$target_dir" ]; then
  find_local_version_file "$target_dir"
else
  find_local_version_file "$RAKUENV_DIR" || {
    [ "$RAKUENV_DIR" != "$PWD" ] && find_local_version_file "$PWD"
  } || echo "${RAKUENV_ROOT}/version"
fi
