#!/usr/bin/env bash
set -e

if [ "$1" = "--debug" ]; then
  export RAKUENV_DEBUG=1
  shift
fi

if [ -n "$RAKUENV_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

abort() {
  { if [ "$#" -eq 0 ]; then cat -
    else echo "rakuenv: $*"
    fi
  } >&2
  exit 1
}

if enable -f "${BASH_SOURCE%/*}"/../libexec/rakuenv-realpath.dylib realpath 2>/dev/null; then
  abs_dirname() {
    local path
    path="$(realpath "$1")"
    echo "${path%/*}"
  }
else
  [ -z "$RAKUENV_NATIVE_EXT" ] || abort "failed to load \`realpath' builtin"

  READLINK=$(type -p greadlink readlink | head -1)
  [ -n "$READLINK" ] || abort "cannot find readlink - are you missing GNU coreutils?"

  resolve_link() {
    $READLINK "$1"
  }

  abs_dirname() {
    local cwd="$PWD"
    local path="$1"

    while [ -n "$path" ]; do
      cd "${path%/*}"
      local name="${path##*/}"
      path="$(resolve_link "$name" || true)"
    done

    pwd
    cd "$cwd"
  }
fi

if [ -z "${RAKUENV_ROOT}" ]; then
  RAKUENV_ROOT="${HOME}/.rakuenv"
else
  RAKUENV_ROOT="${RAKUENV_ROOT%/}"
fi
export RAKUENV_ROOT

if [ -z "${RAKUENV_DIR}" ]; then
  RAKUENV_DIR="$PWD"
else
  [[ $RAKUENV_DIR == /* ]] || RAKUENV_DIR="$PWD/$RAKUENV_DIR"
  cd "$RAKUENV_DIR" 2>/dev/null || abort "cannot change working directory to \`$RAKUENV_DIR'"
  RAKUENV_DIR="$PWD"
  cd "$OLDPWD"
fi
export RAKUENV_DIR


shopt -s nullglob

bin_path="$(abs_dirname "$0")"
for plugin_bin in "${RAKUENV_ROOT}/plugins/"*/bin; do
  PATH="${plugin_bin}:${PATH}"
done
export PATH="${bin_path}:${PATH}"

RAKUENV_HOOK_PATH="${RAKUENV_HOOK_PATH}:${RAKUENV_ROOT}/rakuenv.d"
if [ "${bin_path%/*}" != "$RAKUENV_ROOT" ]; then
  # Add rakuenv's own `rakuenv.d` unless rakuenv was cloned to RAKUENV_ROOT
  RAKUENV_HOOK_PATH="${RAKUENV_HOOK_PATH}:${bin_path%/*}/rakuenv.d"
fi
RAKUENV_HOOK_PATH="${RAKUENV_HOOK_PATH}:/usr/local/etc/rakuenv.d:/etc/rakuenv.d:/usr/lib/rakuenv/hooks"
for plugin_hook in "${RAKUENV_ROOT}/plugins/"*/etc/rakuenv.d; do
  RAKUENV_HOOK_PATH="${RAKUENV_HOOK_PATH}:${plugin_hook}"
done
RAKUENV_HOOK_PATH="${RAKUENV_HOOK_PATH#:}"
export RAKUENV_HOOK_PATH

shopt -u nullglob


command="$1"
case "$command" in
"" )
  { rakuenv---version
    rakuenv-help
  } | abort
  ;;
-v | --version )
  exec rakuenv---version
  ;;
-h | --help )
  exec rakuenv-help
  ;;
* )
  command_path="$(command -v "rakuenv-$command" || true)"
  if [ -z "$command_path" ]; then
    if [ "$command" == "shell" ]; then
      abort "shell integration not enabled. Run \`rakuenv init' for instructions."
    else
      abort "no such command \`$command'"
    fi
  fi

  shift 1
  if [ "$1" = --help ]; then
    if [[ "$command" == "sh-"* ]]; then
      echo "rakuenv help \"$command\""
    else
      exec rakuenv-help "$command"
    fi
  else
    exec "$command_path" "$@"
  fi
  ;;
esac
